"""Add display_label column to category_centroids

Revision ID: 059
Revises: 058
Create Date: 2026-03-29

Stores properly capitalised display labels for categories,
generated by Haiku from the hyphenated slug labels.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "059"
down_revision: Union[str, None] = "058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("category_centroids", sa.Column("display_label", sa.String(100)))


def downgrade() -> None:
    op.drop_column("category_centroids", "display_label")
