"""CVE metadata table for Gemini-generated plain-English summaries.

Revision ID: 015
Revises: 014
Create Date: 2026-04-14

Stores "What you need to know" content for each CVE: what_is_this,
am_i_affected, what_to_do. Generated by Gemini, read by the site
generator. Generation hash tracks staleness — only regenerate if
the CVE's key inputs (description, CVSS, EPSS, KEV) change.
"""
from alembic import op

revision = "015"
down_revision = "014"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        CREATE TABLE IF NOT EXISTS cve_metadata (
            cve_id INTEGER PRIMARY KEY REFERENCES cves(id),
            common_name TEXT,
            what_is_this TEXT,
            am_i_affected TEXT,
            what_to_do TEXT,
            generation_hash TEXT,
            updated_at TIMESTAMPTZ DEFAULT now()
        )
    """)


def downgrade():
    op.execute("DROP TABLE IF EXISTS cve_metadata")
